/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#11131b',
        'surface-dim': '#11131b',
        'surface-bright': '#373942',
        'surface-container-lowest': '#0c0e16',
        'surface-container-low': '#191b24',
        'surface-container': '#1d1f28',
        'surface-container-high': '#282a32',
        'surface-container-highest': '#33343e',
        'on-surface': '#e2e1ee',
        'on-surface-variant': '#c4c5d9',
        'inverse-surface': '#e2e1ee',
        'inverse-on-surface': '#2e3039',
        outline: '#8e90a2',
        'outline-variant': '#434656',
        'surface-tint': '#b8c3ff',
        primary: '#b8c3ff',
        'on-primary': '#002388',
        'primary-container': '#2e5bff',
        'on-primary-container': '#efefff',
        'inverse-primary': '#124af0',
        secondary: '#d4bbff',
        'on-secondary': '#41008b',
        'secondary-container': '#6c04de',
        'on-secondary-container': '#d4baff',
        tertiary: '#00dce5',
        'on-tertiary': '#003739',
        'tertiary-container': '#00797e',
        'on-tertiary-container': '#bbfbff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b8c3ff',
        'on-primary-fixed': '#001356',
        'on-primary-fixed-variant': '#0035be',
        'secondary-fixed': '#ebdcff',
        'secondary-fixed-dim': '#d4bbff',
        'on-secondary-fixed': '#270058',
        'on-secondary-fixed-variant': '#5d00c2',
        'tertiary-fixed': '#63f7ff',
        'tertiary-fixed-dim': '#00dce5',
        'on-tertiary-fixed': '#002021',
        'on-tertiary-fixed-variant': '#004f53',
        background: '#11131b',
        'on-background': '#e2e1ee',
        'surface-variant': '#33343e',
        /* Tom de aviso ("em andamento") — não faz parte do design system
           oficial do Resenha, mas é necessário para status intermediários;
           mantido em harmonia com a paleta escura. */
        amber: '#ffcb7a',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        glow: '0px 4px 20px rgba(46, 91, 255, 0.3)',
        'glow-soft': '0px 4px 20px rgba(46, 91, 255, 0.15)',
        'glow-tertiary': '0 0 20px rgba(0, 220, 229, 0.35)',
      },
    },
  },
  plugins: [],
};
